os: Visual Studio 2015
    
platform: Any CPU
configuration: Release

version: 1.0.{build}

#branches:
#  only:
#  - develop

install:
- ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

before_build:
  - ps: Vsix-IncrementVsixVersion -versionType revision | Vsix-UpdateBuildVersion
  - ps: Vsix-TokenReplacement src\source.extension.cs 'Version = "([0-9\\.]+)"' 'Version = "{version}"'
  - nuget restore -verbosity quiet

build_script:
  - msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

build:
  verbosity: minimal

after_build:
  - ps: Vsix-PushArtifacts | Vsix-PublishToGallery
