// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.183
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Essentials.VS
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string EvsPackageString = "6359da17-6477-4e9c-8e73-7d05ea8a33a1";
        public const string EvsCommandSetString = "4eac4e23-4909-4dac-9d6e-819bdc861480";
        public static Guid EvsPackage = new Guid(EvsPackageString);
        public static Guid EvsCommandSet = new Guid(EvsCommandSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MainMenu = 0xA000;
        public const int EvsToolbar = 0xA001;
        public const int EvsMenu = 0xA002;
        public const int CodeEditorGroup = 0xB000;
        public const int SolutionNodeGroup = 0xC000;
        public const int ProjectGroup = 0xD000;
        public const int BuildGroup = 0x0310;
        public const int RebuildProjectCommand = 0x0315;
        public const int RebuildSolutionCommand = 0x0316;
        public const int CancelBuildCommand = 0x0317;
        public const int VisualStudioGroup = 0x0840;
        public const int ExtensionsAndUpdatesCommand = 0x0845;
        public const int RestartGroup = 0x0900;
        public const int RestartDropDown = 0x0901;
        public const int RestartCommands = 0x0902;
        public const int RestartNormalCommand = 0x0905;
        public const int RestartElevatedCommand = 0x0906;
        public const int OptionsGroup = 0x0950;
        public const int OptionsDropDown = 0x0951;
        public const int OptionsCommands = 0x0952;
        public const int KeyboardOptionsCommand = 0x0955;
        public const int InsertGroup = 0x0A00;
        public const int InsertGuidCommand = 0x0A01;
        public const int EditSolutionCommand = 0x0B01;
        public const int CloseSolutionCommand = 0x0B02;
        public const int EditProjectCommand = 0x0C01;
    }
}
