// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.9.178
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Essentials.VS
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string EvsPackageString = "6359da17-6477-4e9c-8e73-7d05ea8a33a1";
        public const string EvsCommandSetString = "4eac4e23-4909-4dac-9d6e-819bdc861480";
        public static Guid EvsPackage = new Guid(EvsPackageString);
        public static Guid EvsCommandSet = new Guid(EvsCommandSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MainMenu = 0xA000;
        public const int EvsToolbar = 0xA001;
        public const int EvsMenu = 0xA002;
        public const int CodeEditorGroup = 0xB000;
        public const int SolutionGroup = 0xC000;
        public const int BuildGroup = 0x4010;
        public const int RebuildProjectCommand = 0x4015;
        public const int RebuildSolutionCommand = 0x4016;
        public const int CancelBuildCommand = 0x4017;
        public const int VisualStudioGroup = 0x4040;
        public const int ExtensionsAndUpdatesCommand = 0x4045;
        public const int RestartGroup = 0x0100;
        public const int RestartDropDown = 0x0101;
        public const int RestartCommands = 0x0102;
        public const int RestartNormalCommand = 0x0105;
        public const int RestartElevatedCommand = 0x0106;
        public const int EditSolutionCommand = 0xC001;
    }
}
