// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.9.178
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Essentials.VS
{
    static class Vsix
    {
        public const string Id = "049c7ac5-ba44-4a72-b4ee-7be7fb1b0edd";
        public const string Name = "Yann's Essentials for VS";
        public const string Description = "A collection of essential productivity enhancements for day-to-day developing in Visual Studio.";
        public const string Language = "en-US";
        public const string Version = "0.2.1";
        public const string Author = "Yann Duran";
        public const string Tags = ">visual studio, productivity enhancements, essentials, yannduran, yd";
    }
}
