// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.9.178
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Essentials.VS
{
    static class Vsix
    {
        public const string Id = "049c7ac5-ba44-4a72-b4ee-7be7fb1b0edd";
        public const string Name = "Essentials for VS";
        public const string Description = "The simplest way of restarting VIsual Studio on demand (normal and elevated).";
        public const string Language = "en-US";
        public const string Version = "0.1.3";
        public const string Author = "Yann Duran";
        public const string Tags = "";
    }
}
